language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 8.16.1

addons:
   apt:
     packages:
       # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
       - libgconf-2-4

install:
  - npm install -g npm@6.4.1
  - npm install -g gulp
  - npm ci

script:
  - npm run storybook-ci </dev/null &>/dev/null &
  - npm run test-carbon-build
  - npm run lint ./src ./fixtures && npm test -- --maxWorkers=2
  - npm run test-storybook-smoke
  - wait-on http://localhost:9001
  - npm run test-cypress-build

before_deploy: if [ "$TRAVIS_BRANCH" == "release" ]; then ASSETS_PREFIX=https://carbon.sage.com npm run build; fi

deploy:
  - provider: s3
    bucket: carbon.sage.com
    skip_cleanup: true
    local_dir: deploy
    detect_encoding: true
    on:
      branch: release
    access_key_id:
      secure: iZx7SkuMjUMXLVQNO5LSjF6EfQeqGbgdGtPg0hfzVIEcS5s/79j5aq8aQJ7EjCXM+yPRDZMaXB+StXOZjNhEbKLYt2mZDyMki3gAII2QM2MAeI5YtltgJHlXClsMjFiomTbRPo/F9CnIerRBdAFUmQXh2BVSdz86ptsLWs9SrcSjgN/RM6bWSaFYbyckyRVQZVipHYN1vmbEw8ZNZGSQTEPyi3Pw4nXMJ+9ro/72Pt5Ioo3a/praWJL9I5hEc6uBAfFZTtsg70txARaSOycoHxQT8S/xfIzfPQXSmj3n4MTMMCOi3CyJFJfTOdHnQ2ylSllae3zLgIJv1dPQoRuPrB0A1loG2BA+1PXA7KZrwBzYty20XMM2o2tB4mlkKh8p1gOjdsAyRT415kDkEvGpw/b+jFPQ+mAg67ELCJz/HTvBvrKF8nAGsoiG0A1Bi89wxi2riMjAZ2VzbTHrTq/Lp/MlJYt4Z44CXVSKXlKBVKwlDVS7+OIp5QAC0AggtJGFb4kvS/6zUnoykM/lsRBX99lsMURlpGq/EKC5B4iU26NWvF4L+sO9UUesN7LMr8C6oSc7wVrhLHiQbJx55UZTjT4+H/Y4VOFOiEhVKKJTk0/jt/QOOxZbuyhMitLOMBTQQ9tEICv7fIFSUIfePD3bG6FR3vXvod0ct/H7/DhNM0A=
    secret_access_key:
      secure: qdS1pq1ZXvw6lXLrGtSaZTpx7OLREvV/7UCwPFbfQkuQBLbxLe32qlzOkkEQWd7sHwadSgvVTKvX4HKaAIx+QZ2XXFbXGx4HIOCws6ynAVVa2kV5SSHKMwiy+R6Ypttu3GD6uKEhPMUULCYuCLzIIvAOKoCaDIzzKlxzK+g/tCe94J+fKU0DS6U23FFxW51UADgTxn7opg3mkhsteaRyAtDkurAeobEzfQpTFKPNXJ3YcFjpGUf9Z5zxcXXNohKZQP4wODgYU+OZuif/cAeETChWxVThk0PMIIk9/lmwyX1UKIpWpyVTDEKXzwnO2COVWOxtVCpTB0uwfZTZ8MhVXRvFj8Dk/iw+2NN/W55fQ44xx0h6mvhMle98jKTWi6AR/F0LJMpCkZeNTVCdiDz7Ow1g23HlBIRx/seYxph2vLSLkh63kU8ygaOFWhCNdCGOOPLHi8m8X8vlLRvN9ETWY/sMWkvY/S9bXIGw8lv5Bk4lIxAmjoU05XJceq5rOlSax46d1fsicJ5gF6tcxvMau2bFGMCgeZJEpRYChqTEt284woFc8+maa4SwMVrim6J8R53Xfx8mtgCnRlgZmXymzyxu8wCVnAza24iQ4kWmx+fDw70iU5Q3nxSwjN4Q922QZiAFLGpAK0nRDFhE7NPftubYOgsisNCFOnTTTBGJghI=
  - provider: npm
    email: sageoneplatform@sage.com
    api_key:
      secure: M9MjNzeuvNsUl5CTcftbCeUJ3Yf8x8ownH+QZDCsYLy+mp9quDCSUsS1Q3/2kQ33WNfe6B3XBAGwSbnVUc3TPRM/zo0YCTPllMGl3qTRW7AnWEM/9Sqe69f8nAmui4tClf8UaUHk/irWNRmNpqQtFmlFW5jz6CtGXNAinLdHnl2DgvUWhKtbkAlAYn3pZOyrTRxEBdWBErS5yiGkfooY2Iqzw0UQSS6ZIpS5hL+GgWXYrgUHRC27mItVBYS1qBZY9MBVWfj5KP+y4M3+0E+sbZYBYw627ikEkFandc0jumfUgEUPk95iGKy8xrRc/JzPOVEQUKDJYXrtLsz12+DV8RngwXgQwKDOqtHbV52x8xr84Ouo5hEdTecuP3x0dBQkRW5GRE0J3L3A81SqcyBJ8dujUwCCjJL/p7vYtLYS9ouvIszU2keqCNB4F1x9r3tmY6vAmRAjwH6SkoI0kk618klh/jrf78cpSCAe43HS/YltFvs6xOd6rFvtIc6SDJHSjvuZUebV/v6YTx3iDVTPEH9ljlZmwl4r1KnfyW++avgw5fpGMUxJ/n4/BrC2y4M4XJSqZJxv3gt8KUcw8nSJilE4V5NGzOGEfwo9Ki2DPVidFqUvakuhgO5mb6BnyBCbULgE09X8UygbA5tVWkq659bVmpd2WkUziR4KC8Naook=
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^((v[0-9]+.[0-9]+.[0-9]+)(-rc[0-9]+)?)$"
env:
  global:
    - secure: A6uo2bE4JeItW6IIXIcKHYkvGdxoMGZR07jaYbRd3MXvrFwbEg3Re8TybkcYa2GInMZObvBaIeoXjPjxUy3OtjzINmUCAcIiMMWMIQFjLcGP7TMEIr4e/RfFILz0TgLFGN6AH+oe6EM+RevY0tTFD/clfw6DFjrWxBlufZOozv7qqTdjZrgjw52gJmjfOus+FnHZ6117kZ2LPYPqBrmS3r9yLqqh49o8HwM4IJyTuwy9dVo3uvPvJhzyAvpWNdmiurWQK9vTYWTUcBb+IhP7g9TZZfASoTPx0LaNiPJckru1dpBddNxm2qLoA+hc9rpxog0+HxC+Oy2R7z3Wvm6pS/7EBdjgQ5w7lQVE7570o8GkJX673LP+OSOmgDr0b9tsWUCXx4CJ0QosVWDVpWwuandhZ63zE4uoYt31b5b0ehkXTqzPM6D+o2iWCdIcD+BQn1RxpKFOjPsljaZFApwBHfANlj2DiUM7VHtGQCgL33Wm/r1gWhmU3BlLv+MTSEC1PaF7ftMhpWR8uUs77iiWAnMSR/QWQGLyC+tTaDCD3qdQhE8EZuNooUBg5ncqdeYZzN3MxxhiXYQZnpH4BnkCgVNas5tiJ0B1AtkdAMvMYpW1QRhojyuB5gWOMBg7BaOYYGkR60FnWzzU8vWYtbXQbLS+tyruIUzjSFz1A5+jhHc=
    - secure: o91pqys95xx+qSAbkDUJIxryhQmIgEjGYFt/DZZq58Ll45NU+WG7E0yp7gg9Q9QqreAn7GFL3s02+OCpBQue/jqtF6ephPz4M7axwvGN+8IVdTynwQzdK6PUVJ07Atr9jIDXpmoqPUxmkMpKYKHLx5JjG86TBlLVrG1kWaW5uyXQIkDej3SZGZ8d+/HvO4qGDUZlqwbRhXxYbeC6GnE+P3YXChdzFYbpJDmmMaMZcYIzcbGaTbyVzv9pQfwapZTCfTJincDPYyc0K28NsJGT2li47lDwwekhUB3Vqi/OcQ9thbTPaHklRm5akKIprEZ5SN+iXMyJkFHwAWoBldNVu5sTlkHP+deP1pQ6eX9pfBjV9R95pV7inClij1e5JahPVG4XYFOSKm6k4vORRYB3v4KtRdODguBbr2qWan+951K6+KYpXySoHRv6SxU/Zxl/+YXJwHe0NL9a2Cvfg3k44wzJPBZza4yCjWjNPN8ULij9QkJ0P8rbnLQ17jhsEtSoNNkammixYK3yAKKLtAevb6zssTVzs7bH+T+XWVQMgfGnVjoHd6sB+Ki3miuVVqhDPpBX4AGr+d0BF4fzJBKI82pkz9EWEEPuGj18RQ5CdiZ7gxClamnlWzomACEqlUiJafRz/AJJie/kov63h3iLgIJUNlztqYVkhMBOZKO/TaE=
